# -*- coding: utf-8 -*-
"""손가림및테스트_handtest1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ABI9K4j1rgzJVEODWXzPhgNFYmJ3K341
"""

#셀 1
!pip install mediapipe==0.10.14 opencv-python-headless numpy

#셀 2
from google.colab import files
print("손 동영상 파일(.mp4)을 업로드하세요:")
uploaded = files.upload()
VIDEO_NAME = list(uploaded.keys())[0]
print(f"업로드 완료: {VIDEO_NAME}")

#셀 3
import cv2
import numpy as np
import mediapipe as mp_module
import json
import os
import sys
import time
from typing import List, Dict, Tuple, Optional

# ═══════════════════════════════════════════
#  상수
# ═══════════════════════════════════════════

WRIST = 0
MIDDLE_MCP = 9
MIDDLE_PIP = 10  # 11 → 10으로 수정
MIDDLE_DIP = 11  # 13 → 11로 수정

LANDMARK_NAMES = [
    "WRIST",
    "THUMB_CMC", "THUMB_MCP", "THUMB_IP", "THUMB_TIP",
    "INDEX_MCP", "INDEX_PIP", "INDEX_DIP", "INDEX_TIP",
    "MIDDLE_MCP", "MIDDLE_PIP", "MIDDLE_DIP", "MIDDLE_TIP",
    "RING_MCP", "RING_PIP", "RING_DIP", "RING_TIP",
    "PINKY_MCP", "PINKY_PIP", "PINKY_DIP", "PINKY_TIP",
]

OCCLUSION_LEVELS = {
    "level1_MCP": MIDDLE_MCP,
    "level2_PIP": MIDDLE_PIP,
    "level3_DIP": MIDDLE_DIP,
}

JOINT_ANGLES = {
    "THUMB_MCP_angle":  (1, 2, 3),
    "THUMB_IP_angle":   (2, 3, 4),
    "INDEX_MCP_angle":  (5, 6, 7),
    "INDEX_PIP_angle":  (6, 7, 8),
    "MIDDLE_MCP_angle": (9, 10, 11),
    "MIDDLE_PIP_angle": (10, 11, 12),
    "RING_MCP_angle":   (13, 14, 15),
    "RING_PIP_angle":   (14, 15, 16),
    "PINKY_MCP_angle":  (17, 18, 19),
    "PINKY_PIP_angle":  (18, 19, 20),
}

# ═══════════════════════════════════════════
#  유틸리티 함수
# ═══════════════════════════════════════════

def normalize_wrist(landmarks_px):
    pts = np.array([lm[:2] for lm in landmarks_px])
    wrist = pts[0]
    centered = pts - wrist
    scale = np.linalg.norm(centered[MIDDLE_MCP]) + 1e-8
    return centered / scale


def compute_joint_angle(landmarks_px, p, j, c):
    vp = np.array(landmarks_px[p][:2])
    vj = np.array(landmarks_px[j][:2])
    vc = np.array(landmarks_px[c][:2])
    v1 = vp - vj
    v2 = vc - vj
    cos_a = np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2) + 1e-8)
    return float(np.degrees(np.arccos(np.clip(cos_a, -1.0, 1.0))))


def compute_all_angles(landmarks_px):
    return {n: compute_joint_angle(landmarks_px, p, j, c)
            for n, (p, j, c) in JOINT_ANGLES.items()}


def occlusion_params(landmarks_px, target_idx):
    w = np.array(landmarks_px[WRIST][:2])

    mcp_indices = [1, 5, 9, 13, 17]
    mcp_avg = np.mean([np.array(landmarks_px[i][:2]) for i in mcp_indices], axis=0)

    base_dist = np.linalg.norm(mcp_avg - w)
    ratio = OCCLUSION_RATIOS[target_idx]
    r = int(base_dist * ratio / 2)

    # 가상 타겟: wrist에서 MCP 방향으로 ratio배 지점
    vt_x = w[0] + (mcp_avg[0] - w[0]) * ratio
    vt_y = w[1] + (mcp_avg[1] - w[1]) * ratio

    # 중심 = wrist와 가상 타겟의 중점
    cx = int((w[0] + vt_x) / 2)
    cy = int((w[1] + vt_y) / 2)

    return (cx, cy), r

def classify_visibility(landmarks_px, center, radius):
    result = {}
    for i, name in enumerate(LANDMARK_NAMES):
        lm = landmarks_px[i]
        dist = np.sqrt((lm[0]-center[0])**2 + (lm[1]-center[1])**2)
        result[name] = "occluded" if dist <= radius else "visible"
    return result


def compare_poses(orig_px, test_px, visibility=None):
    orig_angles = compute_all_angles(orig_px)
    test_angles = compute_all_angles(test_px)
    angle_errors = {k: abs(orig_angles[k] - test_angles[k]) for k in JOINT_ANGLES}

    orig_norm = normalize_wrist(orig_px)
    test_norm = normalize_wrist(test_px)
    coord_errors = {LANDMARK_NAMES[i]: float(np.linalg.norm(orig_norm[i] - test_norm[i]))
                    for i in range(21)}

    result = {
        "angle_errors": angle_errors,
        "angle_error_mean": float(np.mean(list(angle_errors.values()))),
        "coord_errors": coord_errors,
        "coord_error_mean": float(np.mean(list(coord_errors.values()))),
    }

    if visibility:
        vis_ae, occ_ae, vis_ce, occ_ce = [], [], [], []
        for name, (p, j, c) in JOINT_ANGLES.items():
            joint_name = LANDMARK_NAMES[j]
            err = angle_errors[name]
            if visibility.get(joint_name) == "occluded":
                occ_ae.append(err)
            else:
                vis_ae.append(err)
        for i, name in enumerate(LANDMARK_NAMES):
            err = coord_errors[name]
            if visibility.get(name) == "occluded":
                occ_ce.append(err)
            else:
                vis_ce.append(err)
        result["visible_angle_error_mean"] = float(np.mean(vis_ae)) if vis_ae else None
        result["occluded_angle_error_mean"] = float(np.mean(occ_ae)) if occ_ae else None
        result["visible_coord_error_mean"] = float(np.mean(vis_ce)) if vis_ce else None
        result["occluded_coord_error_mean"] = float(np.mean(occ_ce)) if occ_ce else None

    return result


# ═══════════════════════════════════════════
#  세그멘테이션
# ═══════════════════════════════════════════

def compute_movements(frames_data):
    movements = []
    prev_px = None
    for frame in frames_data:
        if not frame["detected"] or "landmarks_px" not in frame:
            movements.append(np.nan)
            prev_px = None
            continue
        curr_px = np.array([[frame["landmarks_px"][n]["x"],
                             frame["landmarks_px"][n]["y"]]
                            for n in LANDMARK_NAMES])
        if prev_px is not None:
            movements.append(float(np.sum(np.linalg.norm(curr_px - prev_px, axis=1))))
        else:
            movements.append(0.0)
        prev_px = curr_px
    return np.array(movements)


def segment_video(frames_data, fps, smooth_window=5, static_percentile=30.0, min_static_sec=0.3):
    movements = compute_movements(frames_data)
    valid = ~np.isnan(movements)
    if valid.sum() < 2:
        return None

    kernel = np.ones(smooth_window) / smooth_window
    smoothed = np.convolve(np.nan_to_num(movements, nan=0.0), kernel, mode='same')
    threshold = np.percentile(smoothed[valid], static_percentile)
    labels = ["static" if s <= threshold else "dynamic" for s in smoothed]

    min_frames = max(int(min_static_sec * fps), 1)
    static_segs, dynamic_segs = [], []
    seg_start = 0
    for i in range(1, len(labels)):
        if i == len(labels) - 1 or labels[i] != labels[seg_start]:
            end = i + 1 if i == len(labels) - 1 else i
            if labels[seg_start] == "static" and (end - seg_start) >= min_frames:
                static_segs.append((seg_start, end))
            elif labels[seg_start] == "dynamic":
                dynamic_segs.append((seg_start, end))
            seg_start = i

    return {
        "smoothed_movements": smoothed.tolist(),
        "threshold": float(threshold),
        "static_segments": static_segs,
        "dynamic_segments": dynamic_segs,
        "frame_labels": labels,
    }


def select_pause_frames(static_segments, total_frames, n=3):
    if not static_segments:
        return []
    if len(static_segments) <= n:
        return [{"segment": [s, e], "pause_frame": (s+e)//2}
                for s, e in static_segments]

    section = total_frames / n
    selected = []
    for i in range(n):
        s_start, s_end = i * section, (i + 1) * section
        s_mid = (s_start + s_end) / 2
        best, best_dist = None, float('inf')
        for seg in static_segments:
            seg_mid = (seg[0] + seg[1]) / 2
            if s_start <= seg_mid <= s_end:
                d = abs(seg_mid - s_mid)
                if d < best_dist:
                    best_dist, best = d, seg
        if best is None:
            for seg in static_segments:
                d = abs((seg[0]+seg[1])/2 - s_mid)
                if d < best_dist:
                    best_dist, best = d, seg
        if best:
            pf = (best[0] + best[1]) // 2
            if not any(x["pause_frame"] == pf for x in selected):
                selected.append({"segment": list(best), "pause_frame": pf})

    selected.sort(key=lambda x: x["pause_frame"])
    return selected


# ═══════════════════════════════════════════
#  랜드마크 추출
# ═══════════════════════════════════════════

def extract_landmarks_from_video(video_path, confidence=0.5):
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        raise FileNotFoundError(f"영상을 열 수 없음: {video_path}")

    w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    fps = cap.get(cv2.CAP_PROP_FPS)
    total = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    info = {"width": w, "height": h, "fps": fps, "total_frames": total, "source": video_path}

    mp_hands = mp_module.solutions.hands
    hands = mp_hands.Hands(static_image_mode=False, max_num_hands=1,
                           min_detection_confidence=confidence,
                           min_tracking_confidence=confidence)
    frames = []
    idx = 0
    while True:
        ret, frame = cap.read()
        if not ret:
            break
        rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        result = hands.process(rgb)
        entry = {"frame_idx": idx, "detected": False, "confidence": None}
        if result.multi_hand_landmarks:
            hand = result.multi_hand_landmarks[0]
            px_dict, norm_dict = {}, {}
            for i, lm in enumerate(hand.landmark):
                name = LANDMARK_NAMES[i]
                px_dict[name] = {"x": lm.x * w, "y": lm.y * h, "z": lm.z}
                norm_dict[name] = {"x": lm.x, "y": lm.y, "z": lm.z}
            entry["detected"] = True
            entry["landmarks_px"] = px_dict
            entry["landmarks_norm"] = norm_dict
            if result.multi_handedness:
                entry["confidence"] = result.multi_handedness[0].classification[0].score
        frames.append(entry)
        idx += 1
        if idx % 50 == 0:
            det = sum(1 for f in frames if f["detected"])
            print(f"  {idx}/{total} ({det/idx*100:.0f}% 인식)")

    cap.release()
    hands.close()
    det = sum(1 for f in frames if f["detected"])
    print(f"  완료: {det}/{len(frames)} 프레임 인식 ({det/len(frames)*100:.1f}%)")
    return frames, info


# ═══════════════════════════════════════════
#  가림 영상 생성
# ═══════════════════════════════════════════

def reencode_h264(path):
    """OpenCV 'mp4v'(MPEG-4 Part 2) 출력은 브라우저 <video>에서 디코딩되지 않아
    검은 화면이 된다 -- ffmpeg로 H.264(yuv420p, +faststart)로 재인코딩해 같은
    경로에 덮어쓴다. 프레임 수는 1:1로 유지되므로 랜드마크 정렬에 영향 없음."""
    import shutil, subprocess
    ffmpeg = shutil.which('ffmpeg')
    if ffmpeg is None:
        try:
            import imageio_ffmpeg
            ffmpeg = imageio_ffmpeg.get_ffmpeg_exe()
        except ImportError:
            print(f"  [경고] ffmpeg 없음 -- {path}는 mp4v 그대로라 브라우저에서 재생 불가")
            return
    tmp = path + '.h264tmp.mp4'
    subprocess.run([ffmpeg, '-y', '-v', 'error', '-i', path,
                    '-c:v', 'libx264', '-pix_fmt', 'yuv420p', '-crf', '21',
                    '-movflags', '+faststart', '-an', tmp], check=True)
    os.replace(tmp, path)


def generate_occluded_video(video_path, frames_data, info, target_idx, output_path):
    cap = cv2.VideoCapture(video_path)
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    out = cv2.VideoWriter(output_path, fourcc, info['fps'], (info['width'], info['height']))

    last_c, last_r = None, None
    idx = 0
    while True:
        ret, frame = cap.read()
        if not ret:
            break
        f = frames_data[idx]
        if f["detected"] and "landmarks_px" in f:
            px = [(f["landmarks_px"][n]["x"], f["landmarks_px"][n]["y"],
                   f["landmarks_px"][n]["z"]) for n in LANDMARK_NAMES]
            last_c, last_r = occlusion_params(px, target_idx)
        if last_c and last_r:
            cv2.circle(frame, last_c, last_r, (0, 0, 0), -1)
        out.write(frame)
        idx += 1
    cap.release()
    out.release()
    reencode_h264(output_path)
    print(f"  {output_path} ({idx} frames)")


# ═══════════════════════════════════════════
#  jitter 계산
# ═══════════════════════════════════════════

def compute_jitter(landmarks_list):
    prev = None
    jitters = []
    for px in landmarks_list:
        if px is None:
            prev = None
            continue
        norm = normalize_wrist(px)
        if prev is not None:
            jitters.append(np.linalg.norm(norm - prev, axis=1))
        prev = norm
    if not jitters:
        return None
    arr = np.array(jitters)
    return {
        "overall_mean": float(np.mean(arr)),
        "overall_std": float(np.std(arr)),
        "per_landmark": {LANDMARK_NAMES[i]: float(np.mean(arr[:, i])) for i in range(21)},
    }


def _summarize_errors(error_list, label):
    if not error_list:
        return None
    angles = [e["angle_error_mean"] for e in error_list]
    coords = [e["coord_error_mean"] for e in error_list]
    vis_angles = [e["visible_angle_error_mean"] for e in error_list if e.get("visible_angle_error_mean") is not None]
    occ_angles = [e["occluded_angle_error_mean"] for e in error_list if e.get("occluded_angle_error_mean") is not None]
    return {
        "n_frames": len(error_list),
        "angle_error_mean": float(np.mean(angles)),
        "coord_error_mean": float(np.mean(coords)),
        "visible_angle_mean": float(np.mean(vis_angles)) if vis_angles else None,
        "occluded_angle_mean": float(np.mean(occ_angles)) if occ_angles else None,
    }


print("✅ 코드 로드 완료")

#셀 4
import shutil

OCCLUSION_RATIOS = {
    MIDDLE_MCP: 1.45,
    MIDDLE_PIP: 1.75,
    MIDDLE_DIP: 1.95,
}

output_dir = VIDEO_NAME.replace('.mp4', '') + "_experiment"
os.makedirs(output_dir, exist_ok=True)

print("=" * 60)
print("[1/4] 원본 랜드마크 추출")
print("=" * 60)
frames, info = extract_landmarks_from_video(VIDEO_NAME)

print("\n[2/4] 3단계 가림 영상 생성")
for level, target in OCCLUSION_LEVELS.items():
    out_path = os.path.join(output_dir, f"{level}.mp4")
    generate_occluded_video(VIDEO_NAME, frames, info, target, out_path)

# baseline 복사
shutil.copy2(VIDEO_NAME, os.path.join(output_dir, "baseline_original.mp4"))

print("\n[3/4] 동작 세그멘테이션")
seg = segment_video(frames, info["fps"])
if seg is None:
    print("  ⚠ 세그멘테이션 실패")
    seg = {"static_segments": [], "dynamic_segments": [], "frame_labels": []}

pauses = select_pause_frames(seg["static_segments"], info["total_frames"], n=3)
seg["pause_points"] = pauses
print(f"  정적 구간: {len(seg['static_segments'])}개")
print(f"  동적 구간: {len(seg['dynamic_segments'])}개")
print(f"  정지 시점: {[p['pause_frame'] for p in pauses]}")

# 가림 분류 추가
for level, target in OCCLUSION_LEVELS.items():
    for f in frames:
        if f["detected"] and "landmarks_px" in f:
            px = [(f["landmarks_px"][n]["x"], f["landmarks_px"][n]["y"],
                   f["landmarks_px"][n]["z"]) for n in LANDMARK_NAMES]
            c, r = occlusion_params(px, target)

            if "occlusion_levels" not in f:
                f["occlusion_levels"] = {}
            f["occlusion_levels"][level] = {
                "mask_center": {"x": c[0], "y": c[1]},
                "mask_radius": r,
                "visibility": classify_visibility(px, c, r),
            }


print("\n[4/4] 데이터 저장")
data = {"video_info": info, "frames": frames, "segmentation": seg}
json_path = os.path.join(output_dir, "experiment_data.json")
with open(json_path, 'w', encoding='utf-8') as fout:
    json.dump(data, fout, ensure_ascii=False, indent=2)

print(f"\n✅ PREPARE 완료!")
print(f"출력 폴더: {output_dir}/")

# [셀 5] MODEL TEST

json_path = os.path.join(output_dir, "experiment_data.json")
with open(json_path, 'r') as fin:
    data = json.load(fin)

info = data["video_info"]
orig_frames = data["frames"]
seg = data["segmentation"]
pauses = seg.get("pause_points", [])
labels = seg.get("frame_labels", [])

# 원본 baseline jitter
orig_px_seq = []
for fr in orig_frames:
    if fr["detected"] and "landmarks_px" in fr:
        orig_px_seq.append([(fr["landmarks_px"][n]["x"],
                             fr["landmarks_px"][n]["y"],
                             fr["landmarks_px"][n]["z"]) for n in LANDMARK_NAMES])
    else:
        orig_px_seq.append(None)
baseline_jitter = compute_jitter(orig_px_seq)

print("=" * 60)
print("Model Test")
print("=" * 60)
if baseline_jitter:
    print(f"Baseline jitter: {baseline_jitter['overall_mean']:.4f}")

model_results = {"baseline_jitter": baseline_jitter, "levels": {}}

for level_name, target_idx in OCCLUSION_LEVELS.items():
    video_path = os.path.join(output_dir, f"{level_name}.mp4")
    if not os.path.exists(video_path):
        continue

    print(f"\n{'─'*50}")
    print(f"[{level_name}]")

    occ_frames, _ = extract_landmarks_from_video(video_path)

    static_errors, dynamic_errors = [], []
    static_jitter_px, dynamic_jitter_px = [], []

    for occ_f in occ_frames:
        idx = occ_f["frame_idx"]
        if idx >= len(orig_frames):
            break

        orig_f = orig_frames[idx]
        if not occ_f["detected"] or not orig_f["detected"]:
            if idx < len(labels) and labels[idx] == "static":
                static_jitter_px.append(None)
            else:
                dynamic_jitter_px.append(None)
            continue

        orig_px = [(orig_f["landmarks_px"][n]["x"],
                    orig_f["landmarks_px"][n]["y"],
                    orig_f["landmarks_px"][n]["z"]) for n in LANDMARK_NAMES]
        occ_px = [(occ_f["landmarks_px"][n]["x"],
                   occ_f["landmarks_px"][n]["y"],
                   occ_f["landmarks_px"][n]["z"]) for n in LANDMARK_NAMES]

        occ_info = orig_f.get("occlusion_levels", {}).get(level_name, {})
        c = (occ_info["mask_center"]["x"], occ_info["mask_center"]["y"])
        r = occ_info["mask_radius"]
        vis = classify_visibility(orig_px, c, r)
        comp = compare_poses(orig_px, occ_px, vis)

        is_static = idx < len(labels) and labels[idx] == "static"
        if is_static:
            static_errors.append(comp)
            static_jitter_px.append(occ_px)
        else:
            dynamic_errors.append(comp)
            dynamic_jitter_px.append(occ_px)

    # 정지 시점 정확도
    pause_results = []
    for pp in pauses:
        pf = pp["pause_frame"]
        if pf < len(orig_frames) and pf < len(occ_frames):
            orig_f = orig_frames[pf]
            occ_f = occ_frames[pf]
            if orig_f["detected"] and occ_f["detected"]:
                orig_px = [(orig_f["landmarks_px"][n]["x"],
                            orig_f["landmarks_px"][n]["y"],
                            orig_f["landmarks_px"][n]["z"]) for n in LANDMARK_NAMES]
                occ_px_p = [(occ_f["landmarks_px"][n]["x"],
                             occ_f["landmarks_px"][n]["y"],
                             occ_f["landmarks_px"][n]["z"]) for n in LANDMARK_NAMES]
                occ_info = orig_f.get("occlusion_levels", {}).get(level_name, {})
                c = (occ_info["mask_center"]["x"], occ_info["mask_center"]["y"])
                r = occ_info["mask_radius"]
                vis = classify_visibility(orig_px, c, r)
                pause_results.append({
                    "pause_frame": pf,
                    "comparison": compare_poses(orig_px, occ_px_p, vis),
                })

    dynamic_jitter = compute_jitter(dynamic_jitter_px)
    additional = None
    if dynamic_jitter and baseline_jitter:
        additional = dynamic_jitter["overall_mean"] - baseline_jitter["overall_mean"]

    level_result = {
        "static_accuracy": _summarize_errors(static_errors, "static"),
        "dynamic_accuracy": _summarize_errors(dynamic_errors, "dynamic"),
        "pause_point_accuracy": pause_results,
        "dynamic_jitter": dynamic_jitter,
        "additional_jitter": additional,
    }
    model_results["levels"][level_name] = level_result

    print(f"  Static: {len(static_errors)} frames, Dynamic: {len(dynamic_errors)} frames")
    if pause_results:
        for pr in pause_results:
            c = pr["comparison"]
            occ_msg = c.get('occluded_angle_error_mean', 'N/A')
            if isinstance(occ_msg, float):
                occ_msg = f"{occ_msg:.1f} deg"
            print(f"  Pause frame {pr['pause_frame']}: angle error {c['angle_error_mean']:.1f} deg, occluded {occ_msg}")
    if additional is not None:
        print(f"  Additional jitter: {additional:.4f}")

result_path = os.path.join(output_dir, "model_test_results.json")
with open(result_path, 'w') as fout:
    json.dump(model_results, fout, ensure_ascii=False, indent=2)
print(f"\nResults saved: {result_path}")

# [셀 7] Stacked bar — 자체 계산 버전

import matplotlib.pyplot as plt

ANGLE_THRESHOLD = 10.0

fig, ax = plt.subplots(figsize=(8, 6))

level_short = []
good_pcts = []
bad_pcts = []
fail_pcts = []

for lv, target_idx in OCCLUSION_LEVELS.items():
    video_path = os.path.join(output_dir, f"{lv}.mp4")
    if not os.path.exists(video_path):
        continue

    print(f"[{lv}] Analyzing...")
    occ_frames_l, _ = extract_landmarks_from_video(video_path)

    total = len(occ_frames_l)
    n_good = 0
    n_bad = 0
    n_fail = 0

    for occ_f in occ_frames_l:
        idx = occ_f["frame_idx"]
        if idx >= len(orig_frames):
            break

        orig_f = orig_frames[idx]

        # 가림 영상에서 손 인식 실패
        if not occ_f["detected"]:
            n_fail += 1
            continue

        # 원본도 인식 안 된 프레임은 비교 불가 → 제외
        if not orig_f["detected"]:
            continue

        orig_px = [(orig_f["landmarks_px"][n]["x"],
                    orig_f["landmarks_px"][n]["y"],
                    orig_f["landmarks_px"][n]["z"]) for n in LANDMARK_NAMES]
        occ_px = [(occ_f["landmarks_px"][n]["x"],
                   occ_f["landmarks_px"][n]["y"],
                   occ_f["landmarks_px"][n]["z"]) for n in LANDMARK_NAMES]

        angles_orig = compute_all_angles(orig_px)
        angles_occ = compute_all_angles(occ_px)
        mean_err = np.mean([abs(angles_orig[k] - angles_occ[k]) for k in JOINT_ANGLES])

        if mean_err < ANGLE_THRESHOLD:
            n_good += 1
        else:
            n_bad += 1

    print(f"  Total: {total}, Good: {n_good}, Bad: {n_bad}, Fail: {n_fail}")

    if total > 0:
        good_pcts.append(n_good / total * 100)
        bad_pcts.append(n_bad / total * 100)
        fail_pcts.append(n_fail / total * 100)
    else:
        good_pcts.append(0)
        bad_pcts.append(0)
        fail_pcts.append(0)

    level_short.append(lv.replace("level", "L").replace("_", "\n"))

x = np.arange(len(level_short))
w = 0.5

p1 = ax.bar(x, good_pcts, w, color='#4CAF50', label=f'Detected, error < {ANGLE_THRESHOLD} deg')
p2 = ax.bar(x, bad_pcts, w, bottom=good_pcts, color='#FF9800', label=f'Detected, error >= {ANGLE_THRESHOLD} deg')
p3 = ax.bar(x, fail_pcts, w, bottom=[g+b for g, b in zip(good_pcts, bad_pcts)],
            color='#F44336', label='Detection failed')

for i in range(len(level_short)):
    if good_pcts[i] > 5:
        ax.text(x[i], good_pcts[i]/2, f'{good_pcts[i]:.0f}%',
                ha='center', va='center', fontweight='bold', color='white', fontsize=14)
    if bad_pcts[i] > 5:
        ax.text(x[i], good_pcts[i] + bad_pcts[i]/2, f'{bad_pcts[i]:.0f}%',
                ha='center', va='center', fontweight='bold', color='white', fontsize=14)
    if fail_pcts[i] > 5:
        ax.text(x[i], good_pcts[i] + bad_pcts[i] + fail_pcts[i]/2, f'{fail_pcts[i]:.0f}%',
                ha='center', va='center', fontweight='bold', color='white', fontsize=14)

ax.set_ylabel('% of Total Frames')
ax.set_title('MediaPipe Performance by Occlusion Level')
ax.set_xticks(x)
ax.set_xticklabels(level_short)
ax.set_ylim(0, 105)
ax.legend(loc='upper right')
ax.grid(axis='y', alpha=0.3)

plt.tight_layout()
plt.savefig(os.path.join(output_dir, 'performance_stacked_chart.png'), dpi=150)
plt.show()

# [셀 7] 결과 파일 다운로드

from google.colab import files
import zipfile

zip_name = output_dir + ".zip"
with zipfile.ZipFile(zip_name, 'w') as zf:
    for root, dirs, fnames in os.walk(output_dir):
        for fname in fnames:
            fpath = os.path.join(root, fname)
            zf.write(fpath)

files.download(zip_name)
print(f"✅ {zip_name} 다운로드 시작!")